#端口，项目上下文根
server:
  port: 8081
  servlet:
    context-path: /blog
    
#配置mybatis
mybatis:
  #配置xml映射路径
  mapper-locations: classpath:mapper/*.xml
   #配置实体类的别名
  type-aliases-package: com.xm.entity
  configuration:
    #开启驼峰命名法
    map-underscore-to-camel-case: true
    

#配置mysql连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miss?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#    hikari:
#      minimum-idle: 3
#      maximum-pool-size: 10
#      max-lifetime: 30000 #不能小于30秒，否则默认回到1800秒
#      connection-test-query: SELECT 1
  redis:
   host: 127.0.0.1
   port: 6379
   databse: 0


#文件大小 MB必须大写
#  maxFileSize 是单个文件大小
#  maxRequestSize是设置总上传的数据大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 200MB

